spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true

logging:
  level:
    com.locator360: INFO

kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.locator360.core.domain.location
        spring.json.value.default.type: com.locator360.core.domain.location.Location
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

loki:
  host: ${LOKI_HOST:localhost}
  port: ${LOKI_PORT:3100}
